---
- name: Configure Layer 3 Networks on Each router
  hosts: all
  gather_facts: False
  #vars_files:
  # - ./host_vars/R1.yaml
  connection: network_cli

  tasks:
    - name: Create L3_Interfaces
      loop: "{{ l3_fabric.interfaces }}"
      ios_l3_interface:
        name: "{{ item.name }}"
        ipv4: "{{ item.ip_address }}"
    - name: Enable the Interfaces
      loop: "{{ l3_fabric.interfaces }}"
      ios_interfaces:
       config:
        - name: "{{ item.name }}"
          description: "{{ item.desc }}"
          enabled: true