ospfv2:
    processes:
    -   network:
        -   address: 172.20.0.0
            area: '0'
            wildcard_bits: 0.0.0.255
        -   address: 172.23.0.0
            area: '0'
            wildcard_bits: 0.0.255.255
        -   address: 192.168.1.3
            area: '0'
            wildcard_bits: 0.0.0.0
        process_id: 1
        router_id: 10.10.10.13
