---
local_loopbacks:
    - name: Loopback11
      desc: Sample Network Route Injection
      ip_address: 172.21.0.1/24
#      prefix: 24
    - name: Loopback12
      desc: Sample Network Route Injection
      ip_address: 172.21.1.1/24
#      prefix: 24
    - name: Loopback10
      desc: Sample Network Route Injection
      ip_address: 10.10.10.10/32

l3_fabric:
    interfaces:
        - name: Ethernet1/0
          desc: L3 Link to R3
          ip_address: 172.16.0.5/30
         # prefix: 30
        - name: Ethernet1/1
          desc: L3 Link to R2
          ip_address: 172.16.0.1/30
         # prefix: 30

as_number: 65000
log_neighbor_changes: true
router_id: 192.168.1.1
         
neighbor:
-   address: 172.16.0.2
    remote_as: 65000
-   address: 172.16.0.6
    remote_as: 65001

networks:
- prefix: 172.21.0.1
  masklen: 32
- prefix: 172.21.1.1
  masklen: 32
- prefix: 10.10.10.10
  masklen: 32

